[package]
name = "webster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prelude = "0.2.1"
threads = "0.1.0"
thread = "0.1.0"
joinhandle = "0.0.0"